CC=gcc
CFLAGS=-Wall

EXE=\
	getpid \
	fork_example_1 \
	fork_example_2 \
	system_example \
	system_implement_1 \
	system_implement_2 \
	exec_example \
	envp \
	args \

all: ${EXE}

clean:
	rm -rf ${EXE}
