CC=gcc
CFLAGS=-Wall -O0

EXE=\
	addr \
	constant \
	access_code \
	global_vs_static \
	data_vs_bss \
	bss_small \
	bss_large \
	data_small \
	data_large \
	global_1gb \
	global_3gb \
	global_4gb \
	stack \
	max_stack \
	malloc_distance \
	oom_v1 \
	oom_v2 \
	code_start \

all: ${EXE}

clean:
	rm -f ${EXE} *~
